### ISSUE TITLE
申請フォームエディターでエラーが発生する

### ISSUE THREAD

**Issue by hosakou** [SofPyon/inaka-portal#126]
- 申請フォームエディターにはアクセスできるが 追加 変更 の操作をするとエラーになる
- Status Code: 419

**Comment by SofPyon** [comment]
@hosakou 

ごめん！少し時間ができたので、時間差で（ちゃんと動くかわからない）不具合対処を入れました！

該当のコミット → https://github.com/SofPyon/inaka-portal/commit/83451ee60184ceec55ba4c264c5fae9c423fd10d

こちらがちゃんと動くかどうかわからないので、確かめてもらい、必要であれば修正するという感じでお願いしたいです！

**Comment by SofPyon** [comment]
@hosakou 
ごめん！まだエラーになるっぽい…
（419 エラー）

**Comment by SofPyon** [comment]
とりあえず解決したので close
