### ISSUE TITLE
暗号化されたCookieに謎の接頭辞「ENC_」が付与されてしまう

### ISSUE THREAD

**Issue by SofPyon** [SofPyon/inaka-portal#131]
## 再現環境
さくらのレンタルサーバー
（本番環境のみで再現）

## 不具合の内容
- 謎の「ENC_」という接頭辞がついた Cookie
- 「2020_session」という謎の Cookie

![image](https://user-images.githubusercontent.com/6687653/71301754-b4251200-23e6-11ea-8707-d00a51de95fe.png)

- ローカル環境(Docker)では問題ない

![image](https://user-images.githubusercontent.com/6687653/71301765-e20a5680-23e6-11ea-80ed-0e34f801d581.png)

**Comment by SofPyon** [comment]
おそらくこのバグが原因で #126 が発生したと思われる

Axios の機能として、XSRF-TOKEN という Cookie が存在すれば、それを自動的に X-XSRF-TOKEN という HTTP ヘッダにして送ってくれるという機能があるが、「ENC_」という接頭辞が邪魔してしまい、Axios が XSRF-TOKEN を送ってくれなかった。

結果として Laravel が 419 エラーを返していたと思われる。

- - - - -

追記(2020/01/16): さくらのレンサバの WAF のせいだった。WAF は、接頭辞「ENC_」を付けて Cookie を暗号化するだけでなく、httponly にしてしまうらしい。

Cookie の暗号化自体は Laravel 側でも動作するので、WAF が Cookie を暗号化する処理は冗長と言える。とはいえ、WAF を有効にしたほうが安心感が高いので、とりあえず WAF の利用は継続する。

**Comment by hosakou** [comment]
http://blog.inasoft.org/article/102947798.html
「ENC_」はこのページによると WAF のせいらしいです！

**Comment by SofPyon** [comment]
@hosakou 
そういうことか！ありがとう！！
そういえば何となく WAF オンにしてた…笑

原因が分かったのと、今のところ ENC_ のせいで不都合が生じているわけではなさそうなので、この issue は閉じます！
