### ISSUE TITLE
【スケジュール(v2)】説明が空欄の場合にエラーが出力される

### ISSUE THREAD

**Issue by hosakou** [SofPyon/inaka-portal#198]
## 動作環境

- Ubuntu
- Chromium

## バグの説明

- スケジュールの「説明」が null のときにエラーが出てしまう

## スクリーンショット（あれば）
![image](https://user-images.githubusercontent.com/8391342/73455538-9e2a4a00-43b3-11ea-8d2c-3ec289fcd785.png)

## 再現方法
1. スタッフモード > スケジュール管理 から 「説明」を入力していない予定を作成する
1. v2のスケジュールへアクセス

**Comment by SofPyon** [comment]
@hosakou 
issue作成ありがとう！よく見つけたね

こちらですが、summary メソッドに渡される $text が empty だった場合、空文字(`''`)をreturnする、という感じにするのが良いかと思います！

というわけで、対応お願いします！
