### ISSUE TITLE
【ログアウト】ログアウトしたときにエラーが表示される

### ISSUE THREAD

**Issue by hosakou** [SofPyon/inaka-portal#231]
## 動作環境

- Chrome

## スクリーンショット（あれば）
![image](https://user-images.githubusercontent.com/8391342/74600356-c44e2a80-50d3-11ea-9391-b46c146bd69d.png)

## 再現方法
1. ログインしてない場合ログインする
1. ログアウトすると、エラーが出る

**Comment by SofPyon** [comment]
@hosakou 
Oh…これ僕の修正が原因ですね、ごめん！
こちら修正お願いしたいです！

**Comment by SofPyon** [comment]
@hosakou 
…と思ったけど、やっぱ僕の方でやっておきます！
