### ISSUE TITLE
「ログイン状態を維持する」が機能していない？

### ISSUE THREAD

**Issue by SofPyon** [SofPyon/inaka-portal#64]
## 背景
「ログイン状態を維持する」機能は Laravel が標準で持っている機能である。

`remember_web_なんちゃら` という Cookie をセットすることによって、ログイン状態を維持している

…はずが、この Cookie がどうやら機能していない？

-----

ログイン状態は `session_id` という Cookie が管理している。この Cookie が存在しない場合、 Laravel は `remember_web_なんちゃら` という Cookie が存在しているか確認し、存在する場合、この Cookie で自動ログインしてくれるものと僕は認識している。

しかし `session_id` を消すと、自動ログインせず、普通にログイン画面が表示されてしまう。

この原因の調査をお願いしたいです！

**Comment by SofPyon** [comment]
@hosakou 
この issue について補足したので確認お願いします！

**Comment by hosakou** [comment]
@SofPyon 
正しいかはわかりませんがいろいろ試してわかったことを書いておきます！

---
Cookie から `session_id` を削除したときに、新しい `session_id` が生成されてしまい、その時点で `app/Http/Middleware/InjectSessionFromCodeIgniter.php` の 86行目 のところでログアウトされてしまいます。
![image](https://user-images.githubusercontent.com/8391342/75563577-e9f11180-5a8d-11ea-8693-f9bf4ee77b19.png)

LaravelのCookieである `APPNAME_session` の方を消したときはログイン状態が保持されるみたいです(Laravel側にアクセスしたとき)

---
86行目の if文 をコメントアウトすると `session_id` を削除してもログイン状態が保持されるのですが、「ログイン状態を保持する」にチェックしていなくてもログインが保持されてしまいました。

**Comment by SofPyon** [comment]
@hosakou 
調査ありがとう！
なるほど…そんな気がする

であれば、その if 文を削除すれば解決かな…？
修正お願いしても良いでしょうか？

-----

> 86行目の if文 をコメントアウトすると session_id を削除してもログイン状態が保持されるのですが、「ログイン状態を保持する」にチェックしていなくてもログインが保持されてしまいました。

多分、 `session_id` が削除されている場合、 `APPNAME_session` を使ってログインしてしまうからな気がする。両方削除したらログアウトされたので。

( CodeIgniter側ページへアクセス → session_id がない → Laravelのログイン画面へリダイレクトされる → APPNAME_sessionがあるのでログイン中とみなされる → CodeIgniterのセッションにユーザーIDがセットされる → CodeIgniter 側のページへリダイレクトされる )
